name: urbanspoon
channels:
  - conda-forge
dependencies:
  - matplotlib
  - xarray 
  - gcsfs 
  - numpy 
  - matplotlib
  - cartopy 
  - pytest
  - black
  - nc-time-axis
  - zarr
  - dask
  - pip:
      - git+https://github.com/ClimateImpactLab/xclim@63023d27f89a457c752568ffcec2e9ce9ad7a81a